keys:
  users:
    - &walawren age17rp6yw32we7y7q7qjwdqdm2jt9jnv5thqultnuwrmt6w6c8mrfrss3etq4
    - &kiri age1qssz2tujsv8v9shlt7zgxxy7j0k6jawfwhgnzyvfvmckrlpwnqeqwz9lgs
  hosts:
    - &work-wsl age1ms200mnqekyttmvt6n83en7n2hhd6elj2s0h9p264yzuselr74gq0yag7m
    - &nixos-virtualbox age14uvhrejjlxgfapyx5d3lyy2vjy4q6yf22rp0c6nuwr25gechgvdsvacjap
    - &nixos-framework13 age1ppyqus64k2s9vhh5ltccl06uyfjgukxpvvlk3qvmtt394nce2uys330r2c
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *walawren
          - *kiri
          - *work-wsl
          - *nixos-virtualbox
          - *nixos-framework13
