keys:
  users:
    - &walawren age17rp6yw32we7y7q7qjwdqdm2jt9jnv5thqultnuwrmt6w6c8mrfrss3etq4
    - &kiri age1qssz2tujsv8v9shlt7zgxxy7j0k6jawfwhgnzyvfvmckrlpwnqeqwz9lgs
  hosts:
    - &work-wsl age1h63syxkrvy75452dh2s0e6qe70argnaln9v77htst8lnk3632v9q59ur5d
    - &nixos-virtualbox age16qcy63w8tnh4ggnc3s73adhs4dkcnvw8rp8njs5cu3wlgc5mf34q8l254l
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *walawren
          - *kiri
          - *work-wsl
          - *nixos-virtualbox
