name: "CI"

on:
  push:
  workflow_dispatch:

jobs:
  check-flake-lock:
    name: Check Flake Lock
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Nix Flake Checker
        uses: DeterminateSystems/flake-checker-action@v9
        with:
          fail-mode: true

  nix-flake-check:
    name: Check 📋
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: ecarlson94
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run Checks
        run: nix flake check --show-trace

  prepare:
    name: Find NixOS Configurations 🔍
    runs-on: ubuntu-latest
    outputs:
      configurations: ${{ steps.configurations.outputs.configurations }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Find NixOS Configurations 🔍
        id: configurations
        run: nix-instantiate --json --eval --strict -E 'with builtins; attrNames (getFlake (toString ./.)).nixosConfigurations' | perl -pe 's|(.*)|configurations=\1|' >>$GITHUB_OUTPUT

  builds:
    name: Build NixOS Configuration ❄️
    needs: [prepare]
    strategy:
      fail-fast: false
      matrix:
        configuration: ${{ fromJSON(needs.prepare.outputs.configurations) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: ecarlson94
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build Configuration 📋
        run: nix build -L .#nixosConfigurations.${{ matrix.configuration }}.config.system.build.toplevel

  deploy:
    name: Deploy NixOS Configuration 🚀
    if: github.ref == 'refs/heads/master'
    needs: [check-flake-lock, nix-flake-check, builds]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: ecarlson94
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Deploy
        env:
          CACHIX_ACTIVATE_TOKEN: "${{ secrets.CACHIX_ACTIVATE_TOKEN }}"
        run: |
          nix build --print-build-logs .#cachix-deploy-spec
          cachix push ecarlson94 ./result
          cachix deploy activate --async ./result
